language: generic

sudo: required
services:
  - docker

before install:
  - docker build -t arpan9889/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arpan9889/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-633719994672"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY